textbox_width = 212;
textbox_height = 148;
border = 32;
line_sep = 12;
line_width = textbox_width - border*2;
txb_spr = spr_note;
txb_spr_note = spr_note_text;
txb_img = 0;
txb_imgspd = 0;
page = 0;
text[0] = "Gusto mo ba malalaman ang katotohan? Pumunta ka kung saan nangyari ang lahat, bukas ng 9:00pm \n- ken"
text_length[0] = string_length(text[0]);
draw_char = 0;
